# Generated by Django 3.1.3 on 2021-01-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
